# .streamlit/secrets.toml

[connections.snowflake]
account = "QPYXCYF.QL12130"
user = "pkgunwant"
password = "Mother#20184Son"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
